on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        run: exit 1
  important:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: 'Printing out Actual Secret'
        run: echo $SUPER_SECRET | sed 's/./& /g'
        env:
          SUPER_SECRET: ${{ secrets.HI }}
